"""Unit tests for Harbor reward → task status mapping (no Harbor required)."""

from __future__ import annotations

import pytest

from api.schemas import TaskStatus
from api.services.runner import reward_to_task_status


@pytest.mark.parametrize(
    "reward,expected_status,expected_reward",
    [
        (1.0, TaskStatus.passed, 1.0),
        (0.0, TaskStatus.failed, 0.0),
        (None, TaskStatus.error, None),
        (0.5, TaskStatus.failed, 0.5),
    ],
)
def test_reward_to_task_status(reward, expected_status, expected_reward) -> None:
    status, mapped, remarks = reward_to_task_status(reward)
    assert status == expected_status
    assert mapped == expected_reward
    if expected_status == TaskStatus.passed:
        assert remarks is None
    else:
        assert remarks is not None


def test_create_runner_respects_mock_backend() -> None:
    from api.config import BenchmarkConfig, clear_config_cache
    from api.services.runner import MockBenchmarkRunner, create_runner
    from api.store import PostgresRunStore

    clear_config_cache()
    cfg = BenchmarkConfig(
        default_task_ids=["fix-git"],
        default_agent_model="test",
        execution_backend="mock",
    )
    store = PostgresRunStore()
    runner = create_runner(store, config=cfg)
    assert isinstance(runner, MockBenchmarkRunner)
    clear_config_cache()


def test_harbor_runner_rejects_placeholder_agent(tmp_path, monkeypatch) -> None:
    import api.services.runner as runner_mod
    from api.config import BenchmarkConfig
    from api.services.runner import ExecutionUnavailableError, HarborBenchmarkRunner
    from api.store import PostgresRunStore

    agent_dir = tmp_path / "agent"
    agent_dir.mkdir()
    (agent_dir / "agent.py").write_text(
        "# Placeholder — do not edit this file directly.\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(runner_mod, "REPO_ROOT", tmp_path)

    hb = HarborBenchmarkRunner(
        store=PostgresRunStore(),
        config=BenchmarkConfig(
            default_task_ids=["fix-git"],
            default_agent_model="test",
            execution_backend="harbor",
            env_provider="docker",
        ),
    )
    with pytest.raises(ExecutionUnavailableError, match="placeholder"):
        hb._check_agent_import()

